### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by jlag34** [vitaliigrybov/prj-rev-bwfs-dasmoto#1]
Your HTML overall looks really good. You used all of the right elements and your solution looks really good. However, it would be better to wrap your webpage segments with `div`s.

```
<div>
    <h2 id="brushes">Brushes</h2>
     <img src="./resources/img/hacksaw.jpeg" alt="brushes">
     <h3>Hacksaw Brushes</h3>
     <p>Made of the highest qua….</p>
</div>
```

Wrapping each segment with a div will break up your code into more digestible pieces, just like you did for the header. It also makes certain elements of the webpage easy to style.

**Comment by vitaliigrybov** [comment]
Got it. Thank you!
